### ISSUE TITLE
The use of the RES Reddit Enhancement Suite to disable infinite scroll

### ISSUE THREAD

**Issue by paulhaddon** [FlowerForWar/An-Attempt-to-Disable-Reddit-Infinite-Scroll#1]
If you're reading Reddit on a desktop browser, you can install the Reddit Enhancement Suite (RES) extension https://redditenhancementsuite.com/

It has a function to disable the "neverending reddit" feature:

https://www.reddit.com/r/Enhancement/comments/9322ws/infinite_scroll_disable/#res:settings/neverEndingReddit

**Comment by JenieX** [comment]
I did actually try it but doesn't seem to work. Can you confirm that it is working on the new Reddit?
